apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go-worker
        track: go-worker
    spec:
      containers:
        - name: go-worker
          image: gcr.io/nodeasset/go-worker:latest
          ports:
          - containerPort: 80
            name: go-worker
      imagePullSecrets:
        - name: gcr_auth